### PR TITLE
Refactor Text Displays

### PR DESCRIPTION
**Pull request by JadenCooper**
- Made Abstract Interactable Script
- Made Text Displays Interactable
- Collider Set To Trigger So Can Walk Through 
- Made Displays Turn Off After Timer

#28

### CODE REVIEW

**Comment by JadenCooper** [comment]
Just Gotta Change The Display's Image Then This PR Is All Done

**Review by Sharkules — APPROVED** [review]
It's kind of hard to test these changes since the movement system seems to be a little clunky at the moment, but I see no reason this wouldn't work!

Those merge conflicts are a little concerning though. Is there any way to avoid git flipping out on us the next time we make changes to the scene?

**Comment by SB-Lamia** [comment]
> 

my branch will have a movement system. though the text will have to be moved around a little bit... and as for the merge conflicts do you wanna sort them out after gamedev tomorrow?

**Comment by JadenCooper** [comment]
@SB-Lamia  The Reason Why I Removed The Touch Controls Was So The Decoupled Into An Abstract Interactable So The System Can Be Used For Multiple Things. The Other Reason Was The Touch Controls Should Be Used Through Our Chosen Package/Technology (The New Input System) So It Can Be Extendable To Multiple Control Schemes Instead Of Just Touch. I Was Going To Add Touch Interaction When I Did The Mobile Look Issue But You Took Over That With Your Arrow System. So The Only Thing To Do Will Be Adding Mobile Clicking After All Of These Current PR Have Been Merged In

**Comment by JadenCooper** [comment]
@Sharkules I Think Maybe If We Try Prefab Way Next Sprint It Might Help. Meaning Putting All Our Scene Changes Into A Prefab Then Adding Them Back In On Main.

**Pull request merged**
