### PR TITLE
Add updated text to scene

### PR DESCRIPTION
**Pull request by Mcfarlanejo**
I added the information requested. Attached is an image of the update. Let me know what you all think.

image

### CODE REVIEW

**Comment by Mcfarlanejo** [comment]
image
Updated the movement tutorial which then moves on to the normal tutorial screen

**Review by JadenCooper — CHANGES_REQUESTED** [review]
I like the style for the button look alot better than the default ones. I am getting spamed with this error though 
image
I think the movement side of the tutotal should be accessible from the main menu in some way too.  Only other problem I saw now that i'm looking at is the arrow 
image
Needs to be changed to reflect the newer movement arrows.

**Review by JadenCooper — APPROVED** [review]
Looks awesome thank you for adding those requested changes

**Comment by Mcfarlanejo** [comment]
Might be best to merge this one last as it has a lot of scene changes. I also ended up adjusting the main title scene in this branch as I needed the asset for the buttons and it was just easier to do it at the same time haha

**Comment by SB-Lamia** [comment]
everything looks good to me, though the pause menu button cant be clicked. I am assuming that is a different branch but wanted to make sure it was not this branch that was breaking the pause button

**Pull request merged**
