### PR TITLE
Added Tutorial

### PR DESCRIPTION
**Pull request by JadenCooper**
Added A Simple Tutorial Which Is Accessed From The Options Menu

### CODE REVIEW

**Comment by SB-Lamia** [comment]
I like the tutorial screen. it does explain each thing well though there is 3 issues I've noticed.

one the return button clips out of the screen for certain phones. 
image

and two I believe that it should have some sort of prompt when the game starts up. So that people are aware of it without having to go looking for it

I also believe that the tutorial shouldnt be in options. instead should be in the main pause menu as its own button making it easier to find.

**Comment by SB-Lamia** [comment]
though tbf, the first thing might disapear with kait's changes since she fixed alot of the resolution and I dont think this branch has those changes... so it might fix itself after merging.

**Comment by JadenCooper** [comment]
@SB-Lamia Ok Ill Move The The Tutorial To The Base Of The Pause Menu.  Yea I Didn't Mess Too Much With Making Sure Everything Is In Screen Because Of The Stuff That Kate Is Doing. If It Has Problems With That When It Merges Ill Fix It On Main. What Kind Of Prompt Are You Thinking?

**Comment by SB-Lamia** [comment]
I was thinking that you could load that excate menu that has a button that simply just exits out of it. like a popup window that they just read, close and start looking around. it doesnt have to open the pause menu or anything. just be its own thing that displays then vanishes. and if they need it again, maybe add in something at the bottom that you can find this tutorial in the pause menu. if that makes sense.

**Comment by JadenCooper** [comment]
@SB-Lamia Ok ill try add something like that soon. Ill chuck you a @ when its ready to check again.

**Comment by JadenCooper** [comment]
@SB-Lamia Ok I've Added The Tutorial On Startup And Also Brought It Down To The Route Of The Pause Menu

**Pull request merged**
