### PR TITLE
Add option to swap between movement types

### PR DESCRIPTION
**Pull request by Mcfarlanejo**
Added option to swap between click and free movement. Click on one of the options in the start menu to select and then click return, we can change this system later if needed but works as a feature. Hides the arrows in free movement. I will be adding mobile support in another branch.

This is in a new scene file due to scene changes which needed to be made so we can avoid conflicts

### CODE REVIEW

**Review by SB-Lamia — CHANGES_REQUESTED** [review]
I think that the return button should either not be interactable until you click one of the options or just not appear until you click one of them. since I notice you can click it early and menu button appears in the top right.

image

image

**Comment by Mcfarlanejo** [comment]
> I think that the return button should either not be interactable until you click one of the options or just not appear until you click one of them. since I notice you can click it early and menu button appears in the top right.
> 
> image
> 
> image

Forgot about that one before. I've just done a quick script change to resolve the issue

**Review by SB-Lamia — APPROVED** [review]

**Comment by SB-Lamia** [comment]
> > I think that the return button should either not be interactable until you click one of the options or just not appear until you click one of them. since I notice you can click it early and menu button appears in the top right.
> > image
> > image
> 
> Forgot about that one before. I've just done a quick script change to resolve the issue

looks good to me!

**Review by JadenCooper — APPROVED** [review]
Looks good, good fix disabling the return button before an option is selected. In the future though we re probably going to have to move this choice into a screen before the tutorial because the tutorial should be different based upon the choice. Eg describing the different modes of navigation

**Pull request merged**
