### PR TITLE
Re Enabled PC Controls

### PR DESCRIPTION
**Pull request by JadenCooper**
Very small pull request. Just removed an unnecessary check which was preventing mouse input. Now both mobile presses and mouse clicks work

### CODE REVIEW

**Comment by Sharkules** [comment]
You want I should run a build and test?

**Comment by JadenCooper** [comment]
@Sharkules I dont think it needs it. But if you want to be safe and make sure it works go ahead. When I tested the change I tried it in the editor  in simulator and non simulator mode. In both it worked fine.

**Review by Mcfarlanejo — APPROVED** [review]
Looks good to me. Comments are nice and descriptive

**Review by Sharkules — APPROVED** [review]
Tested on pc and ipad, no bugs that I can find.

**Pull request merged**
