### PR TITLE
05 add lights

### PR DESCRIPTION
**Pull request by JadenCooper**
Spot Lights Have Been Added To The Light Fixtures Plus A Simple Light Bulb Model. They Are Turned Off And On By The Light Switches.

### CODE REVIEW

**Comment by Sharkules** [comment]
I'm getting a nullref on water scripts
image

Are there any set up steps that I need to do?

**Comment by JadenCooper** [comment]
@Sharkules The only setup you have to is just bring in the lights prefab directly into the scene hierarchy they should be placed where they need to be. That water error doesn't matter they are from the old sinks that will be removed on the staging branch. They are going to be replaced with the working sinks prefabs.

**Review by Sharkules — CHANGES_REQUESTED** [review]
Looks great, works great! 
We should have workingDoor(2) and workingDoor prime open inwards though, it blocks the move arrow when you get there.
There's also a door just called Door behind workingDoor prime that doesn't do anything
image

**Comment by JadenCooper** [comment]
@Sharkules Wrong Pull Request. But I haven't fully gone over the orientation of all the doors. The Door is behind it because they are going to be removed on the merge to avoid merge errors by not changing the scene

**Comment by Sharkules** [comment]
Correct branch this time!

Lights work great, though I think we should toggle the emission on the bulbs along with enabling the pointlights so the player can see that they've done the lights.
I figured out a pretty easy way to do this, should we do this now or leave it for next sprint?

**Comment by JadenCooper** [comment]
@Sharkules If its fairly easy I think  we could do that now on the staging branch

**Pull request merged**
