### PR TITLE
10 text/arrow overhaul

### PR DESCRIPTION
**Pull request by JadenCooper**
- Changed Display Color 
image

- Displays Will Now Still Appear When in Free Movement
- Fixed Up Location System
- Removed Looking Mobile From Player, Increased Player Speed

### CODE REVIEW

**Comment by Sharkules** [comment]
The top side movement arrows aren't enabling properly. 
Using map move - spawn point arrows appear when you're on the other side of the fence
Spawn arrows appear normally when using other arrows to get there though

image

**Comment by JadenCooper** [comment]
@Sharkules Fixed that problem they just weren't assigned properly.

**Review by Sharkules — APPROVED** [review]
Looks great, works great

**Comment by SB-Lamia** [comment]
looks good to me, cant see anything majorly wrong

**Review by SB-Lamia — APPROVED** [review]

**Pull request merged**
