### PR TITLE
11 notebook button counter

### PR DESCRIPTION
**Pull request by JadenCooper**
- Added A New Notebook Button
- Made The Counter Work Off Of The Scriptable Objects Rather Than The Displays Themselves
- Update Text Displays Colors Across Tutorials And The Counter

This Is What The New Counter Looks Like:
image

### CODE REVIEW

**Comment by Sharkules** [comment]
Closing the collectibles page seems to destroy the UI canvas instead of sending player back to menu. Leftovers from testing, or a problem with my branch? Note: I checked the functionality on my optimisation branch and it works as it should.
Only happens in the collectibles menu, all other menu options seem fine.

Also, the colours for collected/ not collected have a very similar greyness(?) to them. They might be difficult to differentiate for someone with low vision/colourblind. Maybe try yellow/blue? 
These shades test well on [colorfilter](https://www.toptal.com/designers/colorfilter)
image

Also also, I think the book icon needs to be simpler maybe? As an example, these are cute, bold and should be recognisable when very tiny on someone's old phone.
https://www.hiclipart.com/free-transparent-background-png-clipart-iahix
image

Also also also, icon is off center, collectible icons might also be off center?

Very sorry to throw so many issues, I just have many opinions about aesthetics.

**Comment by JadenCooper** [comment]
@Sharkules Just checking for that color change are you meaning changing the text display colors?

**Comment by Sharkules** [comment]
Yes, the text display colours! The pink and the blue

**Comment by JadenCooper** [comment]
@Sharkules Ok i've made those changes tell me what you think please.
This is what it looks like now
image

**Comment by Sharkules** [comment]
@JadenCooper Alternative layout? 

image

**Comment by JadenCooper** [comment]
@Sharkules I like that, looks good. Only problem I have with doing it like that is that it might not be as intuitive that its a button? If that's fine and it still is clickable push those changes because it looks really nice.

**Comment by Sharkules** [comment]
Still fully clickable, I'll push it, definitely double check functionality though!

I did tweak the colours a little, just to make them pop.
Blue - 62D7DB
Orange - F19605

**Comment by Sharkules** [comment]
Start zone
image
Female side room
image
Male main
image

**Review by Sharkules — APPROVED** [review]

**Pull request merged**
