### PR TITLE
09 fence gates interactable

### PR DESCRIPTION
**Pull request by JadenCooper**
Pretty simple branch, just made fence gates open and close.

### CODE REVIEW

**Comment by SB-Lamia** [comment]
how do you interact with the fence gates? I tried click them with mouse, clicking them while looking at them, going to mobile and tapping them but cant get them to open/close :v

**Comment by JadenCooper** [comment]
@SB-Lamia Did you chuck in a working gate to test? I didn't leave them in the scene to avoid scene issues. I should of said that in the pr description.

**Comment by SB-Lamia** [comment]
> @SB-Lamia Did you chuck in a working gate to test? I didn't leave them in the scene to avoid scene issues. I should of said that in the pr description.

ah, that was mybad. I assumed the gate was a prefab already and you had edited the prefab

**Comment by SB-Lamia** [comment]
apart from the animation being abit fast it looks great \o/

**Review by SB-Lamia — APPROVED** [review]

**Pull request merged**
